FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    tcpdump \
    libpcap-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN pip install --no-cache-dir scapy

# keeps container on
CMD ["tail", "-f", "/dev/null"]
