version: '3.8'

services:
  # attacker
  attacker:
    build:
      context: .
      dockerfile: Dockerfile.attacker
    container_name: inquisitor_attacker
    volumes:
      - .:/app
    working_dir: /app
    cap_add:
      - NET_ADMIN # allows crafting raw network packets
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      inquisitor_net:
        ipv4_address: 192.168.1.10
    mac_address: 02:42:c0:a8:01:10
  
  # target 1
  ftp_server:
    image: fauria/vsftpd # light FTP ready-to-deploy
    container_name: inquisitor_server
    environment:
      - FTP_USER=admin
      - FTP_PASS=password
      - PASV_ADDRESS=192.168.1.20 # passive mode
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
    networks:
      inquisitor_net:
        ipv4_address: 192.168.1.20
    mac_address: 02:42:c0:a8:01:20
  
  # target 2
  ftp_client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: inquisitor_client
    networks:
      inquisitor_net:
        ipv4_address: 192.168.1.30
    mac_address: 02:42:c0:a8:01:30
  
# virtual closed network
networks:
  inquisitor_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
